# The URL the site will be built for
base_url = "https://blog.simple-gear.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

title = "Simpe gear"
default_language = "ja"
generate_feed = true

taxonomies = [
    { name = "tags", rss = true }
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
